# WeatherStatistics Makefile by Olivia Stone for Code Clinic: C++
CC		= g++
TARGET	= WeatherStats
SRC		= main.cpp weather_stats.cpp

$(TARGET): $(SRC)
	$(CC) -o $(TARGET) $(SRC)

.PHONY: clean
clean:
	rm -f $(TARGET)